# Generated by Django 4.2.4 on 2024-02-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
