# Generated by Django 4.2.4 on 2024-02-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_application', '0002_alter_note_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id',
            new_name='code',
        ),
    ]
