# Generated by Django 4.2.4 on 2024-02-18 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_application', '0005_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='user',
            new_name='user_id',
        ),
    ]
